version: '3.3'

services:
  api_db:
    container_name: api_db
    image: mysql:5.7
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=api
    networks:
      - api-net

  api_backend:
    container_name: api_backend
    build:
      context: ./backend
    restart: always
    volumes:
      - ./backend:/var/www
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
      - ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    #ports:
    #  - "8000:8000" #debug
    depends_on:
      - api_db
    networks:
      - api-net

  api_frontend:
    container_name: api_frontend
    build:
      context: ./frontend
    restart: always
    volumes:
      - ./frontend:/var/www
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
      - ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    depends_on:
      - api_backend
    networks:
      - api-net

networks:
  api-net:
    driver: bridge
